# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# Smart pane switching with awareness of Vim splits.
# See: https://github.com/christoomey/vim-tmux-navigator
set -g @plugin 'christoomey/vim-tmux-navigator'


# set keybindings
# the following unbind default <prefix> key which is <Ctrl b> to <Ctrl Space>
unbind C-b
# -g flag means global
# to set for a window use the flag -w
set -g prefix C-Space

# reload tmux with a key 
# hit <prefix> r to reload the tmux conf
unbind r
bind r source-file ~/.config/tmux/tmux.conf \; display "Reloaded tmux.conf"


# set the mouse mode on
set -g mouse on 

# some useful defaults for splitting panes
unbind v
unbind h 

unbind % # default for splitting pane vertically
unbind '"' # default for splitting pane horizontally

# the flag -c executes a shell command, and #{pane_current_path} sets the current working directory
# same as the one we just left
bind v split-window -h -c "#{pane_current_path}"
bind h split-window -v -c "#{pane_current_path}"

# bind vim style keys for navigating panes 
# the default is to use arrow keys 
# the flag -n signals that we don't want to use <prefix> key 
bind C-h select-pane -L
bind C-j select-pane -D
bind C-k select-pane -U
bind C-l select-pane -R

# the following command splits the pane vertically
# resizes the pane such that left pane occupies 70% of Space
# and then moves back the cursor to left pane
# bind C-r split-window -h -c "#{pane_current_path}" \; resize-pane -x 70 \; select-pane -L
bind C-r split-window -h -p 30 -c "#{pane_current_path}" \; select-pane -L
bind C-b split-window -v -p 30 -c "#{pane_current_path}" \; select-pane -D

# increase the search limit
set -g history-limit 100000

# set window index to 1 
set -g base-index 1 
set-window-option -g pane-base-index 1 

# use meta key (on mac it's option for me) to go to the next or previous window 
bind -n M-j previous-window
bind -n M-k next-window

# tmux has two modes
# default mode: this allows you to type in terminal (sort of like vim's insert mode)
# copy mode: this allows to navigate the terminal (sort of like vim's normal mode)
# for copy mode using keybindings like that of vim will allow to navigate and search through
# terminal like vim 
# to go into copy mode: <prefix>[, to go back to default mode press q 
set-window-option -g mode-keys vi 


# by default tmux copies from terminal to buffer 
# following changes it to copy it system clipboard 
unbind -T copy-mode-vi Space; # default for begin-selection 
unbind -T copy-mode-vi Enter; # default for copy-selection 

bind -T copy-mode-vi v send-keys -X begin-selection
# reattach-to-user-namespace is required for macos 
# brew install reattach-to-user-namespace
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "reattach-to-user-namespace pbcopy"

# this plugin packs in advance capabilities for copying 
# search using regex and search strings 
# use n and N to jump to next or previous match
set -g @plugin 'tmux-plugins/tmux-copycat'

# fuzzy search the terminal 
# to use fuzzy search <prefix>tab 
# hitting Enter will copy the result to clipboard
set -g @plugin 'laktak/extrakto'


# for resizing panes 
# <prefix> M+arrowkeys


# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'github_username/plugin_name#branch'
# set -g @plugin 'git@github.com:user/plugin'
# set -g @plugin 'git@bitbucket.com:user/plugin'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
